name: Just CI test script
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Date
        id : date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Print Date
        run: echo ${{ steps.date.outputs.date }}

